name: exchangeapp
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  
  
  cupertino_icons: ^0.1.3
  http: ^0.12.2
  path_provider: ^1.6.11
  shimmer: ^1.1.1
  provider: ^4.3.2 
  shared_preferences: ^0.5.8
  autocomplete_textfield: ^1.7.3
  toast: ^0.1.5
  flutter_spinkit: ^4.1.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
  fonts:
    - family: Ubuntu
      fonts:
        - asset: fonts/Ubuntu-Regular.ttf
    - family: Srisakdi
      fonts:
        - asset: fonts/Srisakdi-Regular.ttf
    - family: Lato
      fonts:
        - asset: fonts/Lato-Regular.ttf
  assets:
    - images/
